implemented the leaked cards
arijeet-mukherjee/app-mvp-portal pull request #8
Opened 2024-08-21 16:23 UTC by Sarvesh025

![image](https://github.com/user-attachments/assets/4e666036-42f8-4d52-873d-7f005519d6cc)

2024-08-21 17:18 UTC, arijeet-mukherjee commented on src/app/leaked_credentials/page.tsx
> +    const [loader, setLoader] = useState(false);
set loader true initially

2024-08-21 17:20 UTC, arijeet-mukherjee commented on src/app/leaked_credentials/page.tsx
> +            makeWebServiceCall(`${API_BASE_URL}/api/leakCredentialDetails/getAllLeakedCredDetailsByCondition?email=${email}&is_fixed=no`, 'GET', "", jwtToken)
why an api call here ? It is not required

2024-08-21 17:23 UTC, arijeet-mukherjee requested changes
Dont make unnecessary api calls. api call mostly done at useEffect level or some event handlers. Take inspiration from leak cred page how I did to refactor your code

2024-08-23 08:29 UTC, Sarvesh025 commented on src/app/leaked_credentials/page.tsx
> +            makeWebServiceCall(`${API_BASE_URL}/api/leakCredentialDetails/getAllLeakedCredDetailsByCondition?email=${email}&is_fixed=no`, 'GET', "", jwtToken)
changed the function name

2024-08-23 08:29 UTC, Sarvesh025 commented on src/app/leaked_credentials/page.tsx
> +    const [loader, setLoader] = useState(false);
resolved in latest commit

2024-08-23 08:30 UTC, Sarvesh025 commented on src/component/LeakedDetailCard/index.tsx
> +            (async function(){
removed IIFE and implemented disable function on check box

2024-08-23 10:05 UTC, arijeet-mukherjee approved these changes
LGTM

2024-08-23 10:05 UTC, merged